; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -mcpu=hawaii -passes=amdgpu-codegenprepare %s | FileCheck %s

declare void @foo(ptr)

define void @bar() {
; CHECK-LABEL: define void @bar
; CHECK-SAME: () #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[ALLOCA:%.*]] = alloca i32, align 4, addrspace(5)
; CHECK-NEXT:    [[ALLOCA_CAST:%.*]] = addrspacecast ptr addrspace(5) [[ALLOCA]] to ptr
; CHECK-NEXT:    call void @foo(ptr [[ALLOCA_CAST]])
; CHECK-NEXT:    ret void
;
  %alloca = alloca i32, align 4
  call void @foo(ptr %alloca)
  ret void
}
